import { Intro } from "../Intro";
import { RefList } from "../RefList";

export function SequenceSection() {
  return (
    <div className="space-y-5">
      <Intro
        what="SEQUENCE = ตัวสร้างเลขเรียงให้อัตโนมัติ — เหมือน AUTO_INCREMENT ใน MySQL"
        why="Oracle (ก่อน 12c) ไม่มี auto-increment ในตัว — ใช้ SEQUENCE + Trigger สร้าง PK อัตโนมัติ"
        how="CREATE SEQUENCE → ใช้ .NEXTVAL ขอเลขถัดไป, .CURRVAL ดูเลขล่าสุดใน session"
        example={`CREATE SEQUENCE emp_seq START WITH 100 INCREMENT BY 1;\n\nINSERT INTO employees (emp_id, first_name)\nVALUES (emp_seq.NEXTVAL, 'นภดล');`}
      />
      <RefList
        groups={[
          {
            title: "สร้าง / ใช้",
            emoji: "🔢",
            color: "emerald",
            items: [
              {
                name: "CREATE SEQUENCE",
                syntax: "CREATE SEQUENCE name [START WITH n] [INCREMENT BY n]",
                thai: "ตัวเลือกเพิ่มเติม: MAXVALUE / MINVALUE / CYCLE / CACHE",
                example: `CREATE SEQUENCE order_seq
  START WITH    1000
  INCREMENT BY  1
  MAXVALUE      999999
  NOCYCLE
  CACHE         20;`,
                note: "CACHE 20 = pre-allocate 20 ตัวใน memory ลด overhead",
              },
              {
                name: "NEXTVAL",
                syntax: "seq.NEXTVAL",
                thai: "ขอเลขถัดไป — เลขจะเพิ่มทันที (irrespective ของ rollback)",
                example: `SELECT order_seq.NEXTVAL FROM dual;
-- ครั้งแรกได้ 1000
-- ครั้งสองได้ 1001 ...`,
                note: "⚠️ Rollback ไม่ทำให้เลขย้อน — อาจมี gap",
              },
              {
                name: "CURRVAL",
                syntax: "seq.CURRVAL",
                thai: "ดูเลขล่าสุดที่ NEXTVAL คืนมาใน session นี้ (ต้องเคย NEXTVAL ก่อน)",
                example: `INSERT INTO orders (order_id, ...) VALUES (order_seq.NEXTVAL, ...);
INSERT INTO order_items (order_id, ...) VALUES (order_seq.CURRVAL, ...);`,
              },
              {
                name: "ALTER / DROP",
                thai: "เปลี่ยน increment / cache, หรือลบ sequence",
                example: `ALTER SEQUENCE order_seq INCREMENT BY 10;
DROP SEQUENCE order_seq;`,
              },
            ],
          },
          {
            title: "Identity columns (Oracle 12c+)",
            emoji: "✨",
            color: "sky",
            items: [
              {
                name: "GENERATED AS IDENTITY",
                thai: "ตั้งแต่ 12c มี AUTO_INCREMENT แบบ MySQL ในตัว — ใช้ง่ายกว่า SEQUENCE",
                example: `CREATE TABLE orders (
  order_id  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ...
);

INSERT INTO orders (...) VALUES (...);  -- order_id เพิ่มเอง`,
              },
              {
                name: "BY DEFAULT vs ALWAYS",
                thai: "ALWAYS = ห้ามใส่ค่าเอง · BY DEFAULT = ใส่เองได้ ถ้าไม่ใส่ใช้ auto",
                example: `customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY`,
              },
            ],
          },
          {
            title: "Pattern เก่า: Trigger + Sequence",
            emoji: "🛠️",
            color: "violet",
            items: [
              {
                name: "BEFORE INSERT trigger",
                thai: "ตั้ง trigger เรียก seq.NEXTVAL ก่อนทุก INSERT — ทำให้คนใช้ไม่ต้อง explicit",
                example: `CREATE OR REPLACE TRIGGER emp_bi
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
  IF :NEW.emp_id IS NULL THEN
    :NEW.emp_id := emp_seq.NEXTVAL;
  END IF;
END;
/

-- ใช้:
INSERT INTO employees (first_name) VALUES ('นภา');  -- emp_id ใส่ให้เอง`,
              },
            ],
          },
        ]}
      />
    </div>
  );
}
